# These track the column number of each player attribute in playerlist.csv file
# Note that change in csv column order can be edited here.
player_attribute_index:
  telegram_username: 1
  name: 0
  room_number: 3
  house_number: 2
  faculty: 4
  gender: 6
  gender_pref: 5
  year_of_study: 7
  likes: 9
  dislikes: 10
  comments: 8

