# These track the column number of each player attribute in playerlist.csv file
# Note that change in csv column order can be edited here.
player_attribute_index:
  name: 0
  telegram_username: 1
  house_number: 2
  room_number: 3
  faculty: 4
  gender_pref: 5
  gender: 6
  year_of_study: 7
  comments: 8
  likes: 9
  dislikes: 10

generalized_columns:
  special columns:
    gender_pref: 5
    gender: 6

  enum columns: # Either a lower bound and upper bound or a list of values
    house_number:
      index: 2
      allowed_values:
        shan: 4
        ora: 8
        gaja: 12
        tancho: 15
        ponya: 19

    faculty:
      index: 4
      allowed_values:
        - SoC
        - Medicine
        - Dentistry

    year_of_study:
      index: 7
      allowed_values:
        lower_bound: 1
        upper_bound: 5
  text columns:
    name: 0
    telegram_username: 1
    room_number: 3
    comments: 8
    likes: 9
    dislikes: 10